import { Worker } from '../types/main';

const workersData: Worker[] = [
    {
        uuid: 1234,
        fullname: 'Stephen Hawking',
        profileImage: '/avatar.png',
        age: 32,
        sex: 'male',
        expertise: 'Painter',
        mobile: 9014939363,
        fromTime: '00:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1235,
        fullname: 'Daniel Creig',
        profileImage: '/avatar.png',
        age: 32,
        sex: 'male',
        expertise: 'Painter',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1236,
        fullname: 'Cole Sprouse',
        profileImage: '/logo.png',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1237,
        fullname: 'Cole Sprouse',
        profileImage: '/logo.png',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1238,
        fullname: 'Cole Sprouse',
        profileImage: '/logo.png',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1239,
        fullname: 'Cole Sprouse',
        profileImage: '/worker.jpg',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1240,
        fullname: 'Cole Sprouse',
        profileImage: '/worker.jpg',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
    {
        uuid: 1241,
        fullname: 'Cole Sprouse',
        profileImage: '/worker.jpg',
        age: 32,
        sex: 'male',
        expertise: 'Barber',
        mobile: 9014939363,
        fromTime: '10:00',
        toTime: '17:00',
        address: {
            door_no: '19-1',
            street: 'domala street',
            village: 'jinga',
            city: 'vijayawada',
            district: 'Krishna',
            state: 'Andhra Pradesh',
            pincode: 521202,
        },
        location: '17.385044,78.486671',
    },
];

export default workersData;
